// don't edit this autogenerated file!
export default {
  tooltip_port: {
    en:
      "Port for admin interface. It must be available. If running on linux with no root you cannot use ports below 1000.",
    de:
      "Port für die Admin-Seite. Der Port muss frei sein. Unter Linux dürfen nicht root-Anwender nur die Ports über 1000 benutzen.",
    ru: "Порт для интерфейса.",
    pt:
      "Porta para a interface de administração. Ele tem que estar disponível. Se estiver executando no linux sem root, você não pode usar portas abaixo de 1000.",
    nl:
      "Poort voor beheerdersinterface, deze moet beschikbaar zijn. Als u op Linux draait zonder root  kunt u geen poorten onder 1000 gebruiken.",
    fr:
      "Port pour l'interface d'administration. Il doit être disponible. Les utilisateurs non-adminstratifs ne peuvent pas utiliser les ports inférieurs à 1000.",
    it:
      "Porta per l'interfaccia di amministrazione. Deve essere disponibile. Se si esegue su Linux senza accesso root, non è possibile utilizzare le porte inferiori a 1000.",
    es:
      "Puerto para la interfaz de administración. Tiene que estar disponible. Si se ejecuta en linux sin root, no puede utilizar puertos por debajo de 1000.",
    pl:
      "Port dla interfejsu administratora. Musi być dostępny. Jeśli działasz na Linuksie bez roota, nie możesz używać portów poniżej 1000.",
    "zh-cn":
      "admin界面的端口。它必须是可用的。如果没有以root身份运行，则无法使用1000以下的端口。"
  },
  tooltip_secure: {
    en:
      "Enable SSL protocol. Admin will be available via https:// and not http://",
    de:
      "SSL Verschlüsselung aktivieren. Admin-Oberfläche wird unter https:// und nicht mehr unter http:// erreichbar.",
    ru:
      "Активировать протокол SSL. Сайт будет доступен по https:// , а не по http://",
    pt:
      "Habilite o protocolo SSL. O administrador estará disponível através de https:// e não http://",
    nl:
      "Schakel SSL-protocol in. Beheerpagina is beschikbaar via https: // en niet http: //",
    fr:
      "Activer le protocole SSL. L'administration sera disponible uniquement via https:// et non http://",
    it:
      "Abilita il protocollo SSL. L'amministratore sarà disponibile tramite https: // e non più con http: //",
    es:
      "Habilite el protocolo SSL. El administrador estará disponible a través de https: // y no http: //",
    pl:
      "Włącz protokół SSL. Administrator będzie dostępny przez https: //, a nie http: //",
    "zh-cn": "启用SSL协议。admin界面将通过https://而不是http://访问"
  },
  tooltip_thresholdValue: {
    en:
      "If the browser receives too many events in 3 seconds, refresh will be stopped",
    de:
      "Wenn der Browser in 3 Sekunden zu viele Ereignisse empfängt, wird das Update beendet",
    ru:
      "если браузер получает слишком много событий за 3 секунды, обновление будет остановлено",
    pt:
      "Se o navegador receber muitos eventos em 3 segundos, a atualização será interrompida",
    nl:
      "Als de browser te veel gebeurtenissen binnen 3 seconden ontvangt, wordt de update gestopt",
    fr:
      "Si le navigateur reçoit trop d'événements en 3 secondes, la mise à jour sera arrêtée",
    it:
      "Se il browser riceve troppi eventi in 3 secondi, l'aggiornamento verrà interrotto",
    es:
      "Si el explorador recibe muchos eventos en 3 segundos, se detiene la actualización",
    pl:
      "jeśli przeglądarka otrzyma zbyt wiele zdarzeń w ciągu 3 sekund, aktualizacja zostanie zatrzymana",
    "zh-cn": "如果浏览器在3秒内收到太多事件，将停止刷新"
  },
  tooltip_ttl: {
    en:
      "Login timeout. After this time the user will be automatically logged off.",
    de: "Nach diese Zeit wird ein inaktiver Benutzer ausgeloggt.",
    ru:
      "По прошествии этого времени при бездействии пользователь будет разлогинен.",
    pt:
      "Tempo limite de login. Após esse tempo, o usuário será automaticamente desconectado.",
    nl:
      "Time-out aanmelding. Na deze tijd zal de gebruiker automatisch uitloggen.",
    fr: "Passé ce délai, l'utilisateur sera automatiquement déconnecté.",
    it:
      "Timeout di login. Dopo questo tempo l'utente sarà disconnesso automaticamente.",
    es:
      "Tiempo de espera de inicio de sesión. Después de ese tiempo, el usuario se desconectar automáticamente.",
    pl:
      "Limit czasu logowania. Po tym czasie użytkownik zostanie automatycznie wylogowany.",
    "zh-cn": "登录超时时间。超时后用户将自动注销。"
  },
  "users permissions": {
    en: "Users permissions",
    de: "Anwenderrechte",
    ru: "Права доступа",
    pt: "permissões de usuários",
    nl: "gebruikersrechten",
    fr: "Autorisations des utilisateurs",
    it: "Permessi degli utenti",
    es: "permisos de usuario",
    pl: "uprawnienia użytkowników",
    "zh-cn": "用户权限"
  },
  "my test 1": {
    en: "my test 1",
    pt: "meu teste 1",
    de: "mein Test 1",
    fr: "mon test 1",
    nl: "mijn test 1",
    ru: "мой тест 1",
    it: "il mio test 1",
    "zh-cn": "我的测试1",
    es: "mi prueba 1",
    pl: "mój test 1"
  },
  "my test 2 ": {
    en: "my test 2 ",
    de: "Mein test 2 ",
    ru: "Russisch",
    pt: "meu teste 2",
    fr: "mon test 2",
    pl: "mój test 2",
    nl: "mijn test 2",
    es: "mi prueba 2",
    it: "il mio test 2",
    "zh-cn": "我的测试2"
  }
};
